# This is a basic workflow to help you get started with Actions

name: CodeSniffer

# Controls when the workflow will run
on:
  # Triggers the workflow on any php files in PRs
  pull_request:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"
    branches: [ "master", "develop" ]

  # Allow us to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check out the repo under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Install CodeSniffer
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version
      # Lint the modified files
      - uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: **.php
          scope: "files"
          phpcs_path: php phpcs.phar
          standard: PSR12
